version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1_container
      - api2_container
      - api3_container

  api1_container:
    build:
      context: ./api1
    ports:
      - 8081:80

  api2_container:
    build:
      context: ./api2
    ports:
      - 8082:80

  api3_container:
    build:
      context: ./api1
    ports:
      - 8083:80
