version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 85:85
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1_container
      - api2_container
      - api3_container

  api1_container:
    image: api1_image
    ports:
      - 8001:8001

  api2_container:
    image: api2_image
    ports:
      - 8002:8002

  api3_container:
    image: api3_image
    ports:
      - 8003:8003
